
import localFont from 'next/font/local';
import "./globals.css";
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const simplon = localFont({
  src: './Simplon Norm.ttf',
  display: 'swap',
  variable: '--font-simplon',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={simplon.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
